debug: false        # debug log
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.fastcampus.projectboard: debug          # com.fastcampus.projectboard 패키지의 로그 레벨을 디버그로 설정
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: hyebin
    password: thisisTestpw@!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true            # 데이터베이스 연결을 초기화하는 것을 미루고 애플리케이션 구동 중에 필요한 시점에서 연결을 수행
    hibernate:
      ddl-auto: create                # 엔터티 클래스로부터 테이블을 자동으로 생성합니다. (애플리케이션이 시작될 때마다)
#    open-in-view: false
    show-sql: true              # 실행된 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:             # in-memory database => h2
    console:
      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  profiles:
    active: testdb

---
# --- 는 document 분리 -> 여러 개의 document 작성이 가능하다

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=mysql             # H2 인메모리 데이터베이스를 사용하며, mode=mysql로 설정하여 MySQL 모드로 동작하도록 합니다.
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always

# testdb 프로파일이 활성화되면, H2 인메모리 데이터베이스가 MySQL 모드로 동작하며, SQL 초기화가 항상 수행됩니다.
# 이러한 설정은 주로 테스트 환경에서 가볍고 임시로 사용할 수 있는 인메모리 데이터베이스를 구성할 때 활용됩니다.
